server {
    listen 80;
    listen [::]:80;
    server_name pixeledit.polerain.com;

    include /etc/nginx/cloudflare-allow.conf;

    root /var/www/pixel-edit/current;
    index index.html;

    location /.well-known/acme-challenge/ {
        root /var/www/pixel-edit/current;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:js|css|png|jpg|jpeg|gif|svg|webp|ico)$ {
        try_files $uri =404;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }
}
